framework:
    session:
        handler_id: null
        cookie_secure: false       # HTTP local
        cookie_samesite: lax       # 'lax' pour dev local cross-origin
        cookie_httponly: true
        cookie_lifetime: 0


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
