nelmio_cors:
    defaults:
        origin_regex: true
      #TODO: change to frontend site url
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: [ 'Content-Type', 'Authorization', 'X-Requested-With' ]
        expose_headers: [ 'Content-Length' ]
        max_age: 3600
    paths:
        '^/api/': ~
